services:
  postgres:
    image: postgres:16
    container_name: academia-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: academia_user
      POSTGRES_PASSWORD: academia_pass
      POSTGRES_DB: academia_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: